/* Generated By:JavaCC: Do not edit this line. AdilVisitor.java Version 5.0 */
package edu.sdsc.adil;

public interface AdilVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTADILStatement node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTCreateStatement node, Object data);
  public Object visit(ASTLoadStatement node, Object data);
  public Object visit(ASTDeleteStatement node, Object data);
  public Object visit(ASTCreateDataVerse node, Object data);
  public Object visit(ASTCreatEnvironment node, Object data);
  public Object visit(ASTUseEnvironment node, Object data);
  public Object visit(ASTOperator node, Object data);
  public Object visit(ASTOperand node, Object data);
  public Object visit(ASTaction node, Object data);
}
/* JavaCC - OriginalChecksum=a62302ad7baf1c40f1964c6d7fc30342 (do not edit this line) */
