@startuml
AWSMSchedularService->edu.sdsc.awesome.awesomeWeb.awsmnode:getPerfData()
AWSMSchedular->neo4j:getStatData()[]
neo4j-->AWSMSchedularService:data[][]
AWSMSchedular->solr:getStatData()[]
solr-->AWSMSchedularService:data[][]
AWSMSchedular->pgsql:getStatData()[]
pgsql-->AWSMSchedularService:data[][]
AWSMSchedular->neo4j:getStatData()[]
neo4j-->AWSMSchedularService:data[][]
AWSMSchedular->rserver:getStatData()[]
rserver-->AWSMSchedularService:data[][]
AWSMSchedular->computer:getStatData()[]
computer-->AWSMSchedularService:data[][]:push()
neo4j-->AWSMSchedularService:data[][]:push()
solr-->AWSMSchedularService:data[][]:push()
neo4j-->AWSMSchedularService:data[][]:push()
pgsql-->AWSMSchedularService:data[][]:push()
compute-->AWSMSchedularService:data[][]:push()

@enduml