/* Generated By:JavaCC: Do not edit this line. AdilTestTreeConstants.java Version 6.0_beta */
package edu.sdsc.adil;

public interface AdilTestTreeConstants
{
  public int JJTADILSTATEMENT = 0;
  public int JJTSTATEMENT = 1;
  public int JJTIMPORTSTATEMENT = 2;


  public String[] jjtNodeName = {
    "ADILStatement",
    "Statement",
    "ImportStatement",
  };
}
/* JavaCC - OriginalChecksum=302264b2492351a42072f62b2dd11835 (do not edit this line) */
