/* Generated By:JavaCC: Do not edit this line. CypherTreeConstants.java Version 5.0 */
package edu.sdsc.Cypher;

public interface CypherTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTSTATEMENT = 1;
  public int JJTCREATESTATEMENT = 2;
  public int JJTCREATECONSTANTSTATEMENT = 3;
  public int JJTCREATEENTRYSTATEMENT = 4;
  public int JJTMATCHSTATEMENT = 5;
  public int JJTMERGESTATEMENT = 6;
  public int JJTCYPHERNODE = 7;
  public int JJTCYPHEREDGE = 8;
  public int JJTNODEPROPERTY = 9;


  public String[] jjtNodeName = {
    "Expression",
    "Statement",
    "createStatement",
    "createConstantStatement",
    "createEntryStatement",
    "MatchStatement",
    "MergeStatement",
    "cypherNode",
    "CypherEdge",
    "nodeProperty",
  };
}
/* JavaCC - OriginalChecksum=299cd8eaa31bc126605d44cb83e637b0 (do not edit this line) */
