/* Generated By:JJTree&JavaCC: Do not edit this line. AdilConstants.java */
package edu.sdsc.adil;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AdilConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 6;
  /** RegularExpression Id. */
  int GREATERTHANEQUALS = 7;
  /** RegularExpression Id. */
  int MINORTHANEQUALS = 8;
  /** RegularExpression Id. */
  int NOTEQUALSSTANDARD = 9;
  /** RegularExpression Id. */
  int NOTEQUALSBANG = 10;
  /** RegularExpression Id. */
  int CONCAT = 11;
  /** RegularExpression Id. */
  int NOTIN = 12;
  /** RegularExpression Id. */
  int DIGITS = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int EQAL = 18;
  /** RegularExpression Id. */
  int GREATER = 19;
  /** RegularExpression Id. */
  int LESS = 20;
  /** RegularExpression Id. */
  int FBRACKETSTART = 21;
  /** RegularExpression Id. */
  int RETURN = 22;
  /** RegularExpression Id. */
  int FBRACKETEND = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int StartSQBracket = 26;
  /** RegularExpression Id. */
  int EndSQBracket = 27;
  /** RegularExpression Id. */
  int StartCurlyBracket = 28;
  /** RegularExpression Id. */
  int EndCurlyBracket = 29;
  /** RegularExpression Id. */
  int AT = 30;
  /** RegularExpression Id. */
  int IN = 31;
  /** RegularExpression Id. */
  int OPERATOR = 32;
  /** RegularExpression Id. */
  int MINUS = 33;
  /** RegularExpression Id. */
  int CREATE = 34;
  /** RegularExpression Id. */
  int DELETE = 35;
  /** RegularExpression Id. */
  int ALTER = 36;
  /** RegularExpression Id. */
  int LOAD = 37;
  /** RegularExpression Id. */
  int IMPORT = 38;
  /** RegularExpression Id. */
  int DATASOURCE = 39;
  /** RegularExpression Id. */
  int WITH = 40;
  /** RegularExpression Id. */
  int WHERE = 41;
  /** RegularExpression Id. */
  int AND = 42;
  /** RegularExpression Id. */
  int OR = 43;
  /** RegularExpression Id. */
  int STORE = 44;
  /** RegularExpression Id. */
  int TYPE = 45;
  /** RegularExpression Id. */
  int PARTITION = 46;
  /** RegularExpression Id. */
  int BY = 47;
  /** RegularExpression Id. */
  int AS = 48;
  /** RegularExpression Id. */
  int TEMPORALRELATION = 49;
  /** RegularExpression Id. */
  int TEMPORALGRAPH = 50;
  /** RegularExpression Id. */
  int ON = 51;
  /** RegularExpression Id. */
  int REPORT = 52;
  /** RegularExpression Id. */
  int ANALYSIS = 53;
  /** RegularExpression Id. */
  int EXECUTE = 54;
  /** RegularExpression Id. */
  int EVERY = 55;
  /** RegularExpression Id. */
  int PROPERTYGRAPH = 56;
  /** RegularExpression Id. */
  int MATRIX = 57;
  /** RegularExpression Id. */
  int INTEGER = 58;
  /** RegularExpression Id. */
  int STRING = 59;
  /** RegularExpression Id. */
  int TEXT = 60;
  /** RegularExpression Id. */
  int LONG = 61;
  /** RegularExpression Id. */
  int DOUBLE = 62;
  /** RegularExpression Id. */
  int HISTOGRAM = 63;
  /** RegularExpression Id. */
  int VIEW = 64;
  /** RegularExpression Id. */
  int COLLECTION = 65;
  /** RegularExpression Id. */
  int CONNECTION = 66;
  /** RegularExpression Id. */
  int TO = 67;
  /** RegularExpression Id. */
  int FROM = 68;
  /** RegularExpression Id. */
  int LIBRARY = 69;
  /** RegularExpression Id. */
  int DICTIONARY = 70;
  /** RegularExpression Id. */
  int ONTOLOGY = 71;
  /** RegularExpression Id. */
  int WITNESS = 72;
  /** RegularExpression Id. */
  int PROJECT = 73;
  /** RegularExpression Id. */
  int AWSM = 74;
  /** RegularExpression Id. */
  int NODE = 75;
  /** RegularExpression Id. */
  int NODES = 76;
  /** RegularExpression Id. */
  int PATH = 77;
  /** RegularExpression Id. */
  int SELECT = 78;
  /** RegularExpression Id. */
  int ORDER = 79;
  /** RegularExpression Id. */
  int GROUP = 80;
  /** RegularExpression Id. */
  int USE = 81;
  /** RegularExpression Id. */
  int RELATION = 82;
  /** RegularExpression Id. */
  int CSV = 83;
  /** RegularExpression Id. */
  int GRAPHQL = 84;
  /** RegularExpression Id. */
  int JSON = 85;
  /** RegularExpression Id. */
  int XML = 86;
  /** RegularExpression Id. */
  int SCHEMA = 87;
  /** RegularExpression Id. */
  int NULL = 88;
  /** RegularExpression Id. */
  int LIST = 89;
  /** RegularExpression Id. */
  int ENV = 90;
  /** RegularExpression Id. */
  int ANNOTATE = 91;
  /** RegularExpression Id. */
  int FILTER = 92;
  /** RegularExpression Id. */
  int EXECUTESQLPP = 93;
  /** RegularExpression Id. */
  int CONSTRUCTGRAPH = 94;
  /** RegularExpression Id. */
  int CYPHERQUERY = 95;
  /** RegularExpression Id. */
  int EXECUTECYPHER = 96;
  /** RegularExpression Id. */
  int EXECUTESQL = 97;
  /** RegularExpression Id. */
  int FORALL = 98;
  /** RegularExpression Id. */
  int DIGIT = 99;
  /** RegularExpression Id. */
  int LETTER = 100;
  /** RegularExpression Id. */
  int ALPHANUM = 101;
  /** RegularExpression Id. */
  int FIELDNAME = 102;
  /** RegularExpression Id. */
  int UNQUOTED_IDENTIFIER = 103;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 104;
  /** RegularExpression Id. */
  int INPATH = 105;
  /** RegularExpression Id. */
  int OUTPATH = 106;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "<WHITESPACE>",
    "<GREATERTHANEQUALS>",
    "<MINORTHANEQUALS>",
    "<NOTEQUALSSTANDARD>",
    "<NOTEQUALSBANG>",
    "<CONCAT>",
    "<NOTIN>",
    "<DIGITS>",
    "\"+\"",
    "\"!\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"(\"",
    "\"return\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"in\"",
    "<OPERATOR>",
    "\"-\"",
    "\"create\"",
    "\"delete\"",
    "\"alter\"",
    "\"load\"",
    "\"import\"",
    "\"datasource\"",
    "\"with\"",
    "\"where\"",
    "\"and\"",
    "\"or\"",
    "\"store\"",
    "\"type\"",
    "\"partition\"",
    "\"by\"",
    "\"as\"",
    "\"temporalrelation\"",
    "\"temporalgraph\"",
    "\"on\"",
    "\"report\"",
    "\"analysis\"",
    "\"execute\"",
    "\"every\"",
    "\"propertygraph\"",
    "\"matrix\"",
    "\"integer\"",
    "\"string\"",
    "\"text\"",
    "\"long\"",
    "\"double\"",
    "\"histogram\"",
    "\"view\"",
    "\"collection\"",
    "\"connection\"",
    "\"to\"",
    "\"from\"",
    "\"library\"",
    "\"dictionary\"",
    "\"ontology\"",
    "\"witness\"",
    "\"project\"",
    "\"awsm\"",
    "\"node\"",
    "\"nodes\"",
    "\"path\"",
    "\"select\"",
    "\"order\"",
    "\"group\"",
    "\"use\"",
    "\"relation\"",
    "\"csv\"",
    "\"graphql\"",
    "\"json\"",
    "\"xml\"",
    "\"schema\"",
    "\"null\"",
    "\"list\"",
    "\"env\"",
    "\"annotate\"",
    "\"filter\"",
    "\"executesqlpp\"",
    "\"constructgraph\"",
    "\"cypherquery\"",
    "\"executecypher\"",
    "\"executesql\"",
    "\"for\"",
    "<DIGIT>",
    "<LETTER>",
    "<ALPHANUM>",
    "<FIELDNAME>",
    "<UNQUOTED_IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<INPATH>",
    "<OUTPATH>",
  };

}
