/* Generated By:JJTree&JavaCC: Do not edit this line. AdilTokenManager.java */
package edu.sdsc.adil;
import java.io.*;
import java.util.*;
import edu.sdsc.awesome.adil.parser.AdilFirstPass;
import edu.sdsc.awesome.adil.parser.ParserTable.Table;
import javax.json.Json;
import javax.json.JsonObjectBuilder;
import javax.json.JsonObject;
import javax.json.JsonArrayBuilder;
import java.util.ArrayList;
import java.util.List;
import static edu.sdsc.awesome.adil.parser.StatementOperation.ParserUtil.ImportLibraryDBCheck;
import static edu.sdsc.awesome.adil.parser.StatementOperation.ParserUtil.handleCypherQuery;
import static edu.sdsc.awesome.adil.parser.StatementOperation.ParserUtil.handleSQLPPQuery;
import static edu.sdsc.awesome.adil.parser.StatementOperation.ParserUtil.*;

/** Token Manager. */
public class AdilTokenManager implements AdilConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 10:
         jjmatchedKind = 2;
         return jjMoveNfa_0(1, 0);
      case 13:
         jjmatchedKind = 3;
         return jjMoveNfa_0(1, 0);
      case 32:
         jjmatchedKind = 1;
         return jjMoveNfa_0(1, 0);
      case 33:
         jjmatchedKind = 8;
         return jjMoveNfa_0(1, 0);
      case 40:
         jjmatchedKind = 14;
         return jjMoveNfa_0(1, 0);
      case 41:
         jjmatchedKind = 15;
         return jjMoveNfa_0(1, 0);
      case 43:
         jjmatchedKind = 7;
         return jjMoveNfa_0(1, 0);
      case 44:
         jjmatchedKind = 17;
         return jjMoveNfa_0(1, 0);
      case 46:
         jjmatchedKind = 16;
         return jjMoveNfa_0(1, 0);
      case 58:
         jjmatchedKind = 10;
         return jjMoveNfa_0(1, 0);
      case 59:
         jjmatchedKind = 9;
         return jjMoveNfa_0(1, 0);
      case 61:
         jjmatchedKind = 11;
         return jjMoveNfa_0(1, 0);
      case 64:
         jjmatchedKind = 20;
         return jjMoveNfa_0(1, 0);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x240010841000000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x3000600000400000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x4000008800000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x4880060000000000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x401000000000000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x100000004000000L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x2000002000000L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x8004000000000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x20080200000000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x8000000000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x803100000000L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x10000030000000L);
      case 91:
         jjmatchedKind = 18;
         return jjMoveNfa_0(1, 0);
      case 93:
         jjmatchedKind = 19;
         return jjMoveNfa_0(1, 0);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x240010841000000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x3000600000400000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x4000008800000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x4880060000000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x401000000000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x100000004000000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x2000002000000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x8004000000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x20080200000000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x8000000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x803100000000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x10000030000000L);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 0);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x208000000L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0xb000800000L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x416100010000000L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 77:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 78:
         if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x288010040000000L);
      case 79:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1000600002000000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x21080000400000L);
      case 83:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 1;
         }
         break;
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L);
      case 86:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
      case 87:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000000L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0x4800020000000000L);
      case 89:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000100000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x208000000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0xb000800000L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x416100010000000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 110:
         if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x288010040000000L);
      case 111:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1000600002000000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x21080000400000L);
      case 115:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 1;
         }
         break;
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x4800020000000000L);
      case 121:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000100000000L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 1);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x10002000000L);
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000L);
      case 68:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 2;
         }
         break;
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x4800160020400000L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x400200000800000L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x1200400000000000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x21080080000000L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000008104000000L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x18000019000000L);
      case 86:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 2;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x10002000000L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000L);
      case 100:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 2;
         }
         break;
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x4800160020400000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x400200000800000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x1200400000000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x21080080000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000008104000000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x18000019000000L);
      case 118:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 2;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(1, 2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 2);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x8400000L);
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x4800020000000000L);
      case 68:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 3;
         }
         break;
      case 69:
         if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1800000L);
      case 72:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000000L);
      case 74:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000000L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0x210000000000L);
      case 77:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 3;
         }
         break;
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x10400000000000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x208008004000000L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x83000000000L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x20400a0000000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000000L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x404000200000000L);
      case 87:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 3;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x8400000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x4800020000000000L);
      case 100:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 3;
         }
         break;
      case 101:
         if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1800000L);
      case 104:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000000L);
      case 106:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x210000000000L);
      case 109:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 3;
         }
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x10400000000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x208008004000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x83000000000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x20400a0000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x404000200000000L);
      case 119:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 3;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(1, 3);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 3);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 3);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000L);
      case 69:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x2430680000000000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000200000000L);
      case 76:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x3000000000L);
      case 82:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x8004000000L);
      case 83:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x1200000000c00000L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x4800020000000000L);
      case 89:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000L);
      case 101:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x2430680000000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000200000000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x3000000000L);
      case 114:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x8004000000L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x1200000000c00000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4800020000000000L);
      case 121:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 4);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 4);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 4);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000000L);
      case 67:
         return jjMoveStringLiteralDfa6_0(active0, 0x20600000000000L);
      case 69:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 5;
         }
         break;
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0xc000008000000L);
      case 82:
         if ((active0 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x3002083000000000L);
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0x10010000000000L);
      case 84:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x4800020200000000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000000L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x20600000000000L);
      case 101:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 5;
         }
         break;
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0xc000008000000L);
      case 114:
         if ((active0 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x3002083000000000L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x10010000000000L);
      case 116:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x4800020200000000L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 5);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 5);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 5);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa7_0(active0, 0x3000000000L);
      case 69:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x4800000000000000L);
      case 71:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L);
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0x10200000000L);
      case 78:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000000L);
      case 81:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000000000L);
      case 83:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 6;
         }
         break;
      case 84:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x200680000000000L);
      case 85:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000008000000L);
      case 89:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 6;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x3000000000L);
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x4800000000000000L);
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x10200000000L);
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000000L);
      case 113:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000000000L);
      case 115:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 6;
         }
         break;
      case 116:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x200680000000000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000008000000L);
      case 121:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 6;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(1, 6);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 6);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 6);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000000000L);
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0x5000000000000000L);
      case 69:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 7;
         }
         break;
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x600000000000L);
      case 76:
         return jjMoveStringLiteralDfa8_0(active0, 0x3000000000L);
      case 79:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000000L);
      case 82:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000L);
      case 83:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000000000L);
      case 85:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000000L);
      case 89:
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000L);
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000000000L);
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x5000000000000000L);
      case 101:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 7;
         }
         break;
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x600000000000L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x3000000000L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000000L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000L);
      case 115:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000000000L);
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000000L);
      case 121:
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 7);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 7);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 7);
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000L);
      case 69:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000000000L);
      case 71:
         return jjMoveStringLiteralDfa9_0(active0, 0x82000000000L);
      case 78:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 8;
         }
         break;
      case 79:
         return jjMoveStringLiteralDfa9_0(active0, 0x600000000000L);
      case 81:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000000000L);
      case 82:
         return jjMoveStringLiteralDfa9_0(active0, 0x4001000000000L);
      case 84:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000000000L);
      case 89:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000000000000L);
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000L);
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000000000L);
      case 103:
         return jjMoveStringLiteralDfa9_0(active0, 0x82000000000L);
      case 110:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 8;
         }
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x600000000000L);
      case 113:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000000000L);
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x4001000000000L);
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000000000L);
      case 121:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 8);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 8);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 8);
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000L);
      case 71:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000000000L);
      case 76:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000000000000L);
      case 78:
         if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 9;
         }
         else if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 9;
         }
         break;
      case 80:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000000000000L);
      case 82:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000082000000000L);
      case 89:
         if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 9;
         }
         break;
      case 101:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000L);
      case 103:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000000000L);
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000000000000L);
      case 110:
         if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 9;
         }
         else if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 9;
         }
         break;
      case 112:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000000000000L);
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000082000000000L);
      case 121:
         if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 9;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(1, 9);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 9);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 9);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa11_0(active0, 0x82000000000L);
      case 72:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000000000000000L);
      case 76:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000000L);
      case 80:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000000000000L);
      case 82:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000000000000L);
      case 89:
         if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 61;
            jjmatchedPos = 10;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x82000000000L);
      case 104:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000000000000000L);
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000000L);
      case 112:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000000000000L);
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000000000000L);
      case 121:
         if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 61;
            jjmatchedPos = 10;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(1, 10);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 10);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 10);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000001000000000L);
      case 69:
         return jjMoveStringLiteralDfa12_0(active0, 0x4000000000000000L);
      case 80:
         if ((active0 & 0x800000000000000L) != 0L)
         {
            jjmatchedKind = 59;
            jjmatchedPos = 11;
         }
         return jjMoveStringLiteralDfa12_0(active0, 0x82000000000L);
      case 97:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000001000000000L);
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x4000000000000000L);
      case 112:
         if ((active0 & 0x800000000000000L) != 0L)
         {
            jjmatchedKind = 59;
            jjmatchedPos = 11;
         }
         return jjMoveStringLiteralDfa12_0(active0, 0x82000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 11);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 11);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 11);
   }
   switch(curChar)
   {
      case 72:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 12;
         }
         else if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 12;
         }
         break;
      case 80:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000000000000L);
      case 82:
         if ((active0 & 0x4000000000000000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 12;
         }
         break;
      case 84:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000000L);
      case 104:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 12;
         }
         else if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 12;
         }
         break;
      case 112:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000000000000L);
      case 114:
         if ((active0 & 0x4000000000000000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 12;
         }
         break;
      case 116:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 12);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 12);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 12);
   }
   switch(curChar)
   {
      case 72:
         if ((active0 & 0x1000000000000000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 13;
         }
         break;
      case 73:
         return jjMoveStringLiteralDfa14_0(active0, 0x1000000000L);
      case 104:
         if ((active0 & 0x1000000000000000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 13;
         }
         break;
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 13);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 13);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 13);
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa15_0(active0, 0x1000000000L);
      case 111:
         return jjMoveStringLiteralDfa15_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 14);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 14);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 14);
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 15;
         }
         break;
      case 110:
         if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 15;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(1, 15);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream.backup(seenUpto = curPos + 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { throw new Error("Internal Error"); }
   curPos = 0;
   int startsAt = 0;
   jjnewStateCnt = 31;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                     jjCheckNAddStates(0, 2);
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 21)
                        kind = 21;
                  }
                  else if (curChar == 47)
                     jjAddStates(3, 4);
                  else if (curChar == 34)
                     jjCheckNAdd(5);
                  else if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 3;
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAdd(0);
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if (curChar == 61 && kind > 21)
                     kind = 21;
                  break;
               case 4:
                  if (curChar == 34)
                     jjCheckNAdd(5);
                  break;
               case 5:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(5, 6);
                  break;
               case 6:
                  if (curChar == 34 && kind > 67)
                     kind = 67;
                  break;
               case 8:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjAddStates(5, 6);
                  break;
               case 11:
                  if ((0xfc00ffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 12:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 14:
                  if (curChar == 47)
                     jjAddStates(3, 4);
                  break;
               case 15:
                  if (curChar == 47)
                     jjCheckNAddStates(7, 9);
                  break;
               case 16:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 17:
                  if ((0x2400L & l) != 0L && kind > 4)
                     kind = 4;
                  break;
               case 18:
                  if (curChar == 10 && kind > 4)
                     kind = 4;
                  break;
               case 19:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(21, 22);
                  break;
               case 21:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(21, 22);
                  break;
               case 22:
                  if (curChar == 42)
                     jjAddStates(10, 11);
                  break;
               case 23:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(24, 22);
                  break;
               case 24:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(24, 22);
                  break;
               case 25:
                  if (curChar == 47 && kind > 5)
                     kind = 5;
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAddStates(0, 2);
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAdd(27);
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjCheckNAddTwoStates(28, 29);
                  break;
               case 29:
                  if (curChar == 46)
                     jjCheckNAdd(30);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjCheckNAddTwoStates(29, 30);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                     jjCheckNAddStates(0, 2);
                  }
                  else if (curChar == 91)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if (curChar == 96)
                     jjCheckNAdd(8);
                  break;
               case 5:
                  jjAddStates(12, 13);
                  break;
               case 7:
                  if (curChar == 96)
                     jjCheckNAdd(8);
                  break;
               case 8:
                  if ((0xfffffffeffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(8, 9);
                  break;
               case 9:
                  if (curChar == 96 && kind > 67)
                     kind = 67;
                  break;
               case 10:
                  if (curChar == 91)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 11:
               case 12:
                  if ((0xffffffffdfffffffL & l) != 0L)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 13:
                  if (curChar == 93 && kind > 67)
                     kind = 67;
                  break;
               case 16:
                  jjAddStates(7, 9);
                  break;
               case 21:
                  jjCheckNAddTwoStates(21, 22);
                  break;
               case 23:
               case 24:
                  jjCheckNAddTwoStates(24, 22);
                  break;
               case 26:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAddStates(0, 2);
                  break;
               case 27:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAdd(27);
                  break;
               case 28:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjCheckNAddTwoStates(28, 29);
                  break;
               case 30:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjCheckNAddTwoStates(29, 30);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(12, 13);
                  break;
               case 8:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(5, 6);
                  break;
               case 11:
               case 12:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 16:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(7, 9);
                  break;
               case 21:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(21, 22);
                  break;
               case 23:
               case 24:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(24, 22);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 31 - (jjnewStateCnt = startsAt)))
         break;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { break; }
   }
   if (jjmatchedPos > strPos)
      return curPos;

   int toRet = Math.max(curPos, seenUpto);

   if (curPos < toRet)
      for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
         try { curChar = input_stream.readChar(); }
         catch(java.io.IOException e) { throw new Error("Internal Error : Please send a bug report."); }

   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;

   return toRet;
}
static final int[] jjnextStates = {
   27, 28, 29, 15, 20, 8, 9, 16, 17, 19, 23, 25, 5, 6, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\53", "\41", "\73", "\72", "\75", 
null, null, "\50", "\51", "\56", "\54", "\133", "\135", "\100", null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x7fffffffffffcfc1L, 0xeL, 
};
static final long[] jjtoSkip = {
   0x3eL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[31];
private final int[] jjstateSet = new int[62];
protected char curChar;
/** Constructor. */
public AdilTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public AdilTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 31; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
