/* Generated By:JJTree: Do not edit this line. ASTAnnotateWithStoreOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTAnnotateWithStoreOperation extends SimpleNode {
  public ASTAnnotateWithStoreOperation(int id) {
    super(id);
  }

  public ASTAnnotateWithStoreOperation(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dd6a5224803e30f5926a196f98c5f43a (do not edit this line) */
