/* Generated By:JJTree: Do not edit this line. ASTAwesomeSafeFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTAwesomeSafeFunction extends SimpleNode {
  public ASTAwesomeSafeFunction(int id) {
    super(id);
  }

  public ASTAwesomeSafeFunction(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=46d0dffcf72ed05d622f66d4fab9d80c (do not edit this line) */
