/* Generated By:JJTree: Do not edit this line. ASTAwsmCommonSelect.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTAwsmCommonSelect extends SimpleNode {
  public ASTAwsmCommonSelect(int id) {
    super(id);
  }

  public ASTAwsmCommonSelect(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=784bdc0f5484d8ded081f8458694b1a8 (do not edit this line) */
