/* Generated By:JJTree: Do not edit this line. ASTaction.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTaction extends SimpleNode {
  public ASTaction(int id) {
    super(id);
  }

  public ASTaction(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTaction(this, data);
  }
}
/* JavaCC - OriginalChecksum=c69e9a5d5ab07be913bfd8ed9980ed53 (do not edit this line) */
