/* Generated By:JJTree: Do not edit this line. ASTCreateDataSOURCE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTCreateDataSOURCE extends SimpleNode {
  public ASTCreateDataSOURCE(int id) {
    super(id);
  }

  public ASTCreateDataSOURCE(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTCreateDataSOURCE(this, data);
  }
}
/* JavaCC - OriginalChecksum=1a05f9e1a16c42f94332fe1896d82451 (do not edit this line) */
