/* Generated By:JJTree: Do not edit this line. ASTConstructGRAPH.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTConstructGRAPH extends SimpleNode {
  public ASTConstructGRAPH(int id) {
    super(id);
  }

  public ASTConstructGRAPH(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1811fda07f3cdaeae0480ed2461db4e8 (do not edit this line) */
