/* Generated By:JJTree: Do not edit this line. ASTCreateDataVerse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTCreateDataVerse extends SimpleNode {
  public ASTCreateDataVerse(int id) {
    super(id);
  }

  public ASTCreateDataVerse(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c3d24e675dd010017993983fbd04c9a3 (do not edit this line) */
