/* Generated By:JJTree: Do not edit this line. ASTCreateDataSOURCE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTCreateDataSOURCE extends SimpleNode {
  public ASTCreateDataSOURCE(int id) {
    super(id);
  }

  public ASTCreateDataSOURCE(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e04579fa5f69d6bcf2a6a9f7055295ee (do not edit this line) */
