/* Generated By:JJTree: Do not edit this line. ASTCreateStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTCreateStatement extends SimpleNode {
  public ASTCreateStatement(int id) {
    super(id);
  }

  public ASTCreateStatement(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTCreateStatement(this, data);
  }
}
/* JavaCC - OriginalChecksum=8a5d94f30b90924568e84e481e983085 (do not edit this line) */
