/* Generated By:JJTree: Do not edit this line. ASTCreatEnvironment.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTCreatEnvironment extends SimpleNode {
  public ASTCreatEnvironment(int id) {
    super(id);
  }

  public ASTCreatEnvironment(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTCreatEnvironment(this, data);
  }
}
/* JavaCC - OriginalChecksum=cad7c696aaf130a00f535bb359749bd2 (do not edit this line) */
