/* Generated By:JJTree: Do not edit this line. ASTDeclareAnalysis.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTDeclareAnalysis extends SimpleNode {
  public ASTDeclareAnalysis(int id) {
    super(id);
  }

  public ASTDeclareAnalysis(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTDeclareAnalysis(this, data);
  }
}
/* JavaCC - OriginalChecksum=296b7dfd8aad3942ff82d2493c847b1b (do not edit this line) */
