/* Generated By:JJTree: Do not edit this line. ASTDeleteStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTDeleteStatement extends SimpleNode {
  public ASTDeleteStatement(int id) {
    super(id);
  }

  public ASTDeleteStatement(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dcfc7f1efcf066fb4f59b23a4a149976 (do not edit this line) */
