/* Generated By:JJTree: Do not edit this line. ASTExecuteSQLPP.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTExecuteSQLPP extends SimpleNode {
  public ASTExecuteSQLPP(int id) {
    super(id);
  }

  public ASTExecuteSQLPP(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTExecuteSQLPP(this, data);
  }
}
/* JavaCC - OriginalChecksum=058ff88084cd6d3d93edc668b0608f85 (do not edit this line) */
