/* Generated By:JJTree: Do not edit this line. ASTexecuteCypher.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTexecuteCypher extends SimpleNode {
  public ASTexecuteCypher(int id) {
    super(id);
  }

  public ASTexecuteCypher(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTexecuteCypher(this, data);
  }
}
/* JavaCC - OriginalChecksum=a3a2c21af8828442e72d3114f0e96ab4 (do not edit this line) */
