/* Generated By:JJTree: Do not edit this line. ASTFunctionParam.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTFunctionParam extends SimpleNode {
  public ASTFunctionParam(int id) {
    super(id);
  }

  public ASTFunctionParam(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c7b27105198da2dde49aa432d5ad3709 (do not edit this line) */
