/* Generated By:JJTree: Do not edit this line. ASTGetDictionary.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTGetDictionary extends SimpleNode {
  public ASTGetDictionary(int id) {
    super(id);
  }

  public ASTGetDictionary(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b3596a946e9eca3e67e3b868c9ac8b3b (do not edit this line) */
