/* Generated By:JJTree: Do not edit this line. ASTGetConditionExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTGetConditionExpression extends SimpleNode {
  public ASTGetConditionExpression(int id) {
    super(id);
  }

  public ASTGetConditionExpression(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTGetConditionExpression(this, data);
  }
}
/* JavaCC - OriginalChecksum=12a90adec0dc8458153fa1b6989fc451 (do not edit this line) */
