/* Generated By:JJTree: Do not edit this line. ASTImportLibrary.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTImportLibrary extends SimpleNode {
  public ASTImportLibrary(int id) {
    super(id);
  }

  public ASTImportLibrary(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=31b84c8891f34eb071b2b18f5b52ee3c (do not edit this line) */
