/* Generated By:JJTree: Do not edit this line. ASTJsonObjectBuilder.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTJsonObjectBuilder extends SimpleNode {
  public ASTJsonObjectBuilder(int id) {
    super(id);
  }

  public ASTJsonObjectBuilder(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTJsonObjectBuilder(this, data);
  }
}
/* JavaCC - OriginalChecksum=982bfef44a83d7ce5abbce2ceb6c5deb (do not edit this line) */
