/* Generated By:JJTree: Do not edit this line. ASTProjectFunction.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTProjectFunction extends SimpleNode {
  public ASTProjectFunction(int id) {
    super(id);
  }

  public ASTProjectFunction(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTProjectFunction(this, data);
  }
}
/* JavaCC - OriginalChecksum=a827676691a5a5d40c1b2afc4b0d4d04 (do not edit this line) */
