/* Generated By:JJTree: Do not edit this line. ASTPropertyGraphExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTPropertyGraphExpression extends SimpleNode {
  public ASTPropertyGraphExpression(int id) {
    super(id);
  }

  public ASTPropertyGraphExpression(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5016fdfe0e46a48f1d7a95add6a41afa (do not edit this line) */
