/* Generated By:JJTree: Do not edit this line. ASTPropertyGraphExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTPropertyGraphExpression extends SimpleNode {
  public ASTPropertyGraphExpression(int id) {
    super(id);
  }

  public ASTPropertyGraphExpression(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTPropertyGraphExpression(this, data);
  }
}
/* JavaCC - OriginalChecksum=3177d023b34a2eae42debbf328a15a15 (do not edit this line) */
