/* Generated By:JJTree: Do not edit this line. ASTquetedStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTquetedStatement extends SimpleNode {
  public ASTquetedStatement(int id) {
    super(id);
  }

  public ASTquetedStatement(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visitASTquetedStatement(this, data);
  }
}
/* JavaCC - OriginalChecksum=c52623d61df3962cff1bb5ae2e17af40 (do not edit this line) */
