/* Generated By:JJTree: Do not edit this line. ASTUserDefinedFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTUserDefinedFunction extends SimpleNode {
  public ASTUserDefinedFunction(int id) {
    super(id);
  }

  public ASTUserDefinedFunction(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f46dafbf1fb69e3df94a0ca6abd1fcb7 (do not edit this line) */
