/* Generated By:JJTree: Do not edit this line. ASTGetConditionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.SQLPP;

public
class ASTGetConditionExpression extends SimpleNode {
  public ASTGetConditionExpression(int id) {
    super(id);
  }

  public ASTGetConditionExpression(SQLPP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLPPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=030f0ebb62d5d568f19dfedd14b499ea (do not edit this line) */
