/* Generated By:JJTree: Do not edit this line. ASTnotINstatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.SQLPP;

public
class ASTnotINstatement extends SimpleNode {
  public ASTnotINstatement(int id) {
    super(id);
  }

  public ASTnotINstatement(SQLPP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLPPVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d66b2fb3603edabe2a78825716708a34 (do not edit this line) */
