/*
 * Copyright (c) 2019.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *
 */

/* Generated By:JavaCC: Do not edit this line. SQLPPVisitor.java Version 5.0 */
package edu.sdsc.SQLPP;

public interface SQLPPVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTSelectStatement node, Object data);
  public Object visit(ASTGetConditionExpression node, Object data);
  public Object visit(ASTnotINstatement node, Object data);
  public Object visit(ASTAggregate node, Object data);
  public Object visit(ASTSelectStatementWith node, Object data);
  public Object visit(ASTOperator node, Object data);
  public Object visit(ASTOperand node, Object data);
}
/* JavaCC - OriginalChecksum=fdf728183dddecf770ca3e8a1790af1f (do not edit this line) */
