/*
 * Copyright (c) 2019.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *
 */

/* Generated By:JavaCC: Do not edit this line. SQLPPTreeConstants.java Version 5.0 */
package edu.sdsc.SQLPP;

public interface SQLPPTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTSTATEMENT = 1;
  public int JJTSELECTSTATEMENT = 2;
  public int JJTGETCONDITIONEXPRESSION = 3;
  public int JJTNOTINSTATEMENT = 4;
  public int JJTAGGREGATE = 5;
  public int JJTSELECTSTATEMENTWITH = 6;
  public int JJTOPERATOR = 7;
  public int JJTOPERAND = 8;


  public String[] jjtNodeName = {
    "Expression",
    "Statement",
    "SelectStatement",
    "GetConditionExpression",
    "notINstatement",
    "Aggregate",
    "SelectStatementWith",
    "Operator",
    "Operand",
  };
}
/* JavaCC - OriginalChecksum=f66eb9b48c41e3f98c099ed177272cf5 (do not edit this line) */
